version: '3.8'

services:
  api:
    container_name: api
    image: fresh-desk:1.0.0
    environment:
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - FRESHDESK_API_URL=${FRESHDESK_API_URL}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - PASSWORD=${PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: ['nx', 'serve', 'api']
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  web:
    container_name: web
    image: fresh-desk:1.0.0
    environment:
      - NX_BASE_URL=${NX_BASE_URL}
      # - NX_BASE_URL=http://212.227.30.194:3000
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['nx', 'serve', 'web', '--host', '0.0.0.0']
    ports:
      # - 80:4200
      - 4200:4200
    volumes:
      - /usr/src/app/node_modules
