version: '3.8'

services:
  api:
    container_name: api
    hostname: api
    restart: always
    image: fresh-desk:2.0.0
    environment:
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - FRESHDESK_API_URL=${FRESHDESK_API_URL}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - PASSWORD=${PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [ 'nx', 'serve', 'api' ]
    networks:
      - freshdesk-network

  web:
    container_name: web
    hostname: freshdesk
    restart: always
    depends_on:
      - api
    environment:
      - NX_BASE_URL=${NX_BASE_URL}
    build:
      context: .
      dockerfile: ./DockerfileWeb
      args:
        - NX_BASE_URL=${NX_BASE_URL}
    networks:
      - service-hub
      - freshdesk-network

networks:
  freshdesk-network:
    name: freshdesk-network
    driver: bridge
  service-hub:
    name: service-hub
    external: true
